; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
extra_scripts = pre:scripts/patch_safegithubota.py
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	bodmer/TJpg_Decoder@^1.1.0
	gibz104/SafeGithubOTA@^0.1.0
build_flags = 
	-D USER_SETUP_LOADED=1
	-D USE_HSPI_PORT
	-D ILI9341_DRIVER=1
	-D TFT_RGB_ORDER=TFT_BGR
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D TFT_MISO=13
	-D TFT_MOSI=11
	-D TFT_SCLK=12
	-D TFT_CS=5
	-D TFT_DC=7
	-D TFT_RST=6
	-D LOAD_GLCD
	-D LOAD_FONT2
	-D LOAD_FONT4
	-D LOAD_FONT6
	-D LOAD_FONT7
	-D LOAD_FONT8
	-D LOAD_GFXFF
	-D SMOOTH_FONT
	-D TOUCH_CS=-1
	-D SPI_FREQUENCY=40000000
	-D SPI_READ_FREQUENCY=6000000
	-D SPI_TOUCH_FREQUENCY=2500000
	-D SUPPORT_TRANSACTIONS
